### ISSUE TITLE
KuberLogic cert-manager issue

### ISSUE THREAD

**Issue by sarthakdixit89** [kuberlogic/kuberlogic#200]
Hi,
I stuck on 
Waiting for cert-manager to be ready..... 
or getting the error of timout

Kindly help me out

**Comment by ynnt** [comment]
Hi

What version of kuberlogic are you running?

**Comment by sarthakdixit89** [comment]
Hi,
KuberLogic version
cli: 0.0.12
I am currently using this version.

**Comment by ynnt** [comment]
Could you please run this command and provide the generated zip file

```
kuberlogic diag
```

**Comment by sarthakdixit89** [comment]
Created Zip after using cmd  "kuberlogic diag"
[kuberlogic-diag-1663058341.zip](https://github.com/kuberlogic/kuberlogic/files/9555092/kuberlogic-diag-1663058341.zip)

**Comment by sarthakdixit89** [comment]
Hi,
May you please share what will be the diagnose by my shared  **https://github.com/kuberlogic/kuberlogic/files/9555092/kuberlogic-diag-1663058341.zip?**

**Comment by ynnt** [comment]
Please share this command output `kubectl -n cert-manager describe pods`

**Comment by sarthakdixit89** [comment]
kubectl -n cert-manager describe pods
Name:             cert-manager-66bd77df8f-fnnm2
Namespace:        cert-manager
Priority:         0
Service Account:  cert-manager
Node:             <none>
Labels:           app=cert-manager
                  app.kubernetes.io/component=controller
                  app.kubernetes.io/instance=cert-manager
                  app.kubernetes.io/name=cert-manager
                  app.kubernetes.io/version=v1.7.1
                  pod-template-hash=66bd77df8f
Annotations:      prometheus.io/path: /metrics
                  prometheus.io/port: 9402
                  prometheus.io/scrape: true
Status:           Pending
IP:               
IPs:              <none>
Controlled By:    ReplicaSet/cert-manager-66bd77df8f
Containers:
  cert-manager:
    Image:      quay.io/jetstack/cert-manager-controller:v1.7.1
    Port:       9402/TCP
    Host Port:  0/TCP
    Args:
      --v=2
      --cluster-resource-namespace=$(POD_NAMESPACE)
      --leader-election-namespace=kube-system
    Environment:
      POD_NAMESPACE:  cert-manager (v1:metadata.namespace)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-tlbh2 (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  kube-api-access-tlbh2:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  52s   default-scheduler  0/1 nodes are available: 1 node(s) had untolerated taint {node-role.kubernetes.io/control-plane: }. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.


Name:             cert-manager-cainjector-6495667ff4-wc7fc
Namespace:        cert-manager
Priority:         0
Service Account:  cert-manager-cainjector
Node:             <none>
Labels:           app=cainjector
                  app.kubernetes.io/component=cainjector
                  app.kubernetes.io/instance=cert-manager
                  app.kubernetes.io/name=cainjector
                  app.kubernetes.io/version=v1.7.1
                  pod-template-hash=6495667ff4
Annotations:      <none>
Status:           Pending
IP:               
IPs:              <none>
Controlled By:    ReplicaSet/cert-manager-cainjector-6495667ff4
Containers:
  cert-manager:
    Image:      quay.io/jetstack/cert-manager-cainjector:v1.7.1
    Port:       <none>
    Host Port:  <none>
    Args:
      --v=2
      --leader-election-namespace=kube-system
    Environment:
      POD_NAMESPACE:  cert-manager (v1:metadata.namespace)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-7vsw2 (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  kube-api-access-7vsw2:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  52s   default-scheduler  0/1 nodes are available: 1 node(s) had untolerated taint {node-role.kubernetes.io/control-plane: }. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.


Name:             cert-manager-webhook-59d6cdfb6f-hnbfp
Namespace:        cert-manager
Priority:         0
Service Account:  cert-manager-webhook
Node:             <none>
Labels:           app=webhook
                  app.kubernetes.io/component=webhook
                  app.kubernetes.io/instance=cert-manager
                  app.kubernetes.io/name=webhook
                  app.kubernetes.io/version=v1.7.1
                  pod-template-hash=59d6cdfb6f
Annotations:      <none>
Status:           Pending
IP:               
IPs:              <none>
Controlled By:    ReplicaSet/cert-manager-webhook-59d6cdfb6f
Containers:
  cert-manager:
    Image:      quay.io/jetstack/cert-manager-webhook:v1.7.1
    Port:       10250/TCP
    Host Port:  0/TCP
    Args:
      --v=2
      --secure-port=10250
      --dynamic-serving-ca-secret-namespace=$(POD_NAMESPACE)
      --dynamic-serving-ca-secret-name=cert-manager-webhook-ca
      --dynamic-serving-dns-names=cert-manager-webhook,cert-manager-webhook.cert-manager,cert-manager-webhook.cert-manager.svc
    Liveness:   http-get http://:6080/livez delay=60s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get http://:6080/healthz delay=5s timeout=1s period=5s #success=1 #failure=3
    Environment:
      POD_NAMESPACE:  cert-manager (v1:metadata.namespace)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-hwjqj (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  kube-api-access-hwjqj:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  52s   default-scheduler  0/1 nodes are available: 1 node(s) had untolerated taint {node-role.kubernetes.io/control-plane: }. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.

**Comment by turmyshevd** [comment]
@sarthakdixit89 please drop me a line at dturmyshev@cloudlinux.com, I'll send you a video instruction on KuberLogic installation
